# CMake generated Testfile for 
# Source directory: /usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test
# Build directory: /usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_err "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_err")
set_tests_properties(test_err PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;14;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_bn "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_bn")
set_tests_properties(test_bn PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;18;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_dv "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_dv")
set_tests_properties(test_dv PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;22;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_fp "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_fp")
set_tests_properties(test_fp PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;26;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_fpx "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_fpx")
set_tests_properties(test_fpx PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;30;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_fb "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_fb")
set_tests_properties(test_fb PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;34;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_fbx "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_fbx")
set_tests_properties(test_fbx PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;38;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_ep "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_ep")
set_tests_properties(test_ep PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;42;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_epx "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_epx")
set_tests_properties(test_epx PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;46;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_eb "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_eb")
set_tests_properties(test_eb PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;50;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_ed "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_ed")
set_tests_properties(test_ed PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;54;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_ec "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_ec")
set_tests_properties(test_ec PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;58;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_pc "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_pc")
set_tests_properties(test_pc PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;62;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_pp "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_pp")
set_tests_properties(test_pp PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;66;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_md "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_md")
set_tests_properties(test_md PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;70;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_cp "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_cp")
set_tests_properties(test_cp PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;74;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_mpc "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_mpc")
set_tests_properties(test_mpc PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;78;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_rand "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_rand")
set_tests_properties(test_rand PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;81;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
add_test(test_core "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-target/bin/test_core")
set_tests_properties(test_core PROPERTIES  _BACKTRACE_TRIPLES "/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;10;add_test;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;82;ADD_MODULE;/usr1/anawin/Desktop/ABE_software/00.RELIC/test/relic-main/test/CMakeLists.txt;0;")
