f1 = open("complete_result.txt", "r")
f2 = open("/mnt/rose/usr5/masada/nakayama/bls_signature/complete_sim_result.txt", "r")
lines1 = f1.read()
lines2 = f2.read()
l1_split = lines1.split("\n")
l2_split = lines2.split("\n")
print(len(l1_split))
print(len(l2_split))
assert len(l1_split) == len(l2_split)
for i in range(len(l1_split) // 3):
    #x0 = int(l1_split[4 * i], 16)
    #z0 = int(l1_split[4 * i + 1], 16)
    #x1 = int(l1_split[4 * i + 2], 16)
    #z1 = int(l1_split[4 * i + 3], 16)
    #x0_ = int(l2_split[4 * i], 16)
    #z0_ = int(l2_split[4 * i + 1], 16)
    #x1_ = int(l2_split[4 * i + 2], 16)
    #z1_ = int(l2_split[4 * i + 3], 16)
    x = int(l1_split[3 * i], 16)
    y = int(l1_split[3 * i + 1], 16)
    z = int(l1_split[3 * i + 2], 16)
    x_ = int(l2_split[3 * i], 16)
    y_ = int(l2_split[3 * i + 1], 16)
    z_ = int(l2_split[3 * i + 2], 16)
    print(x)
    print(x_)
    assert x == x_
    assert y == y_
    assert z == z_
f1.close()
f2.close()